version: '3.3'

services:
  pg_db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  django:
    container_name: BookingDjango
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "
             python /usr/src/BookingDjango/manage.py makemigrations &&
             python /usr/src/BookingDjango/manage.py migrate --noinput &&
             python /usr/src/BookingDjango/manage.py runserver 0.0.0.0:9000
      "
    volumes:
      - .:/usr/src/BookingDjango
    ports:
      - 9000:9000
    depends_on:
      - pg_db
    restart: always
    env_file:
      - ./.env.dev
volumes:
  pg_data: